---
version: "3.7"

services:
    sentinel:
      tty: true
      network_mode: host
      environment:
      - DEBUG=true
      build:
        context: .
      depends_on:
      - mongodb

    mongodb:
      image: mongo:4.2.8
