name: "Test, build and push"

on:
    workflow_dispatch:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            TEST_NETWORK: 172.100.100.0/24
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prepare environment
              run: |

                # Create test network
                docker network create --subnet $TEST_NETWORK test-network

                # Start test containers
                docker run -itd --hostname test-container-1 --network test-network ubuntu:latest
                docker run -itd --hostname test-container-2 --network test-network ubuntu:latest

            - name: Install dependencies
              run: pip install -r sentinel/requirements.txt

            - name: Build docker image and run tests
              run: |
                docker build -t sentinel .
                docker run --network test-network sentinel pytest

    docker:
      needs: test
      runs-on: ubuntu-latest
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: radeksh/sentinel:latest
